separate links and entities in relationships
odpi/happi-graph pull request #15
Opened 2021-06-29 15:13 UTC by marius-patrascu

2021-06-30 08:34 UTC, sarbull commented
@marius-patrascu this is not really how we discussed, i mentioned you to add types/group in the odpi/egeria-js-commons and dinamically map them in the implementation under happi-graph

this way you will not manually hardcode the titles for links and nodes

2021-06-30 08:36 UTC, sarbull requested changes

2021-06-30 08:36 UTC, sarbull commented on happi-graph-legend.js
> +        <div class="icon-title">Entities</div>
this should come from a groupped map by type/group

2021-06-30 08:36 UTC, sarbull commented on happi-graph-legend.js
> +        <div class="icon-title">Relationships</div>
this should come from a groupped map by type/group

2021-06-30 08:36 UTC, sarbull commented on happi-graph-legend.js
> +      linkLabels: {
this is redundant

2021-07-06 07:12 UTC, marius-patrascu commented
I updated the PR but I still have to improve the code to generate the correct title, at the moment it does not pluralize the group retrieved from egeria js commons

2021-07-07 07:51 UTC, sarbull approved these changes

2021-07-07 07:51 UTC, sarbull commented on happi-graph.js
> +                                legend-data = "{}"
this is internal property, you don't need to add it as an input

2021-07-07 07:51 UTC, sarbull commented on package.json
> +    "@polymer/paper-icon-button": "3.0.2",
these are unused dependencies, right? we can remove them

2021-07-07 07:57 UTC, merged